version: "3.8"

services:
  databasu:
    build:
      context: databases/postgres
      dockerfile: postgres.dockerfile
    container_name: Witch_stash
    env_file:
      - .env
    ports:
      - "5454:5432"
    volumes:
      - ./databases/postgres/dumps/dump.sql:/docker-entrypoint-initdb.d/2dumps.sql
    networks:
      - twitchy_forest
  bot:
    build: .
    container_name: Marisa
    env_file:
      - .env
    command: bash -c 'python Marisa.py'
    depends_on:
      - databasu
      - redis
    volumes:
      - .:/Snow
    networks:
      - twitchy_forest
  redis:
    image: redis:7.0.4
    container_name: Witch_garden
    ports:
      - "2169:2769"
    command: redis-server --requirepass ${RED_PASS:?RED_PASS variable is not set} --save 20 1 --loglevel warning --port 2769
    volumes:
      - ./databases/redis/data:/data
    networks:
      - twitchy_forest
networks:
  twitchy_forest:
    driver: bridge