version: "3.8"

services:
  databasu:
    image: postgres:14.4
    container_name: Witch_stash
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5454:5432"
    networks:
      - twitchy_forest
  bot:
    build: ../.
    container_name: Marisa
    env_file:
      - ../.env
    command: >
      sh -c "flake8 && pytest"
    depends_on:
      - databasu
      - redis
    volumes:
      - ..:/Snow
    networks:
      - twitchy_forest
  redis:
    image: redis:7.0.4
    container_name: Witch_garden
    ports:
      - "2769:2769"
    command: --port 2769
    networks:
      - twitchy_forest
networks:
  twitchy_forest:
    driver: bridge