version: "3.8"

services:
  databasu:
    build:
      context: ../databases/postgres
      dockerfile: postgres.dockerfile
    container_name: Witch_stash
    env_file:
      - ../.env
    ports:
      - "5454:5432"
    networks:
      - twitchy_forest
  bot:
    build: ../.
    container_name: Marisa
    env_file:
      - ../.env
    command: >
      sh -c "mkdir -p reports &&
              flake8 && 
              pytest --html-report=reports/pytest_report --cov=. CI/tests --cov-report html:reports/coverage_html --cov-fail-under=80"
    depends_on:
      - databasu
      - redis
    volumes:
      - ..:/Snow
    networks:
      - twitchy_forest
  redis:
    image: redis:7.0.4
    container_name: Witch_garden
    ports:
      - "2769:2769"
    command: --port 2769
    volumes:
      - ../databases/redis/data:/data
    networks:
      - twitchy_forest
networks:
  twitchy_forest:
    driver: bridge