name: DockerTest

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Making .env'
        run: |
          touch .env
          echo BOT_TOKEN = ${{ secrets.TEST_BOT_TOKEN }} >> .env
          echo POSTGRES_PASSWORD = ${{ secrets.POSTGRES_PW }} >> .env
          echo TEST_CHANNEL_ID = ${{ secrets.TEST_CHANNEL_ID }} >> .env
          echo TEST_USER_ID = ${{ secrets.TEST_USER_ID }} >> .env
      - name: 'Building containers'
        run: docker compose -f CI/Testing.yml build
      - name: 'Testing'
        run: docker compose -f CI/Testing.yml up --abort-on-container-exit
      - name: 'Report upload'
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: pytest_html_report.html