name: DockerTest

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Making .env'
        run: |
          touch .env
          echo BOT_TOKEN = ${{ secrets.TEST_BOT_TOKEN }} >> .env
          echo POSTGRES_PASSWORD = ${{ secrets.POSTGRES_PW }} >> .env
      - name: 'Building containers'
        run: docker compose -f Marisa_flight.yml up -d
      - name: 'Healthcheck'
        run: |
          sleep 5
          docker exec Marisa pytest


      
