name: Witchy pipeline

on:
  workflow_run:
    workflows: [ DockerTest ]
    types:
      - completed


jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: SSH Pipeline
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          connect_timeout: 60s
          script: |
            echo WELCOME
            cd Marisabot
            echo ${{ secrets.PASSWORD }} | sudo -S git pull
            echo ${{ secrets.PASSWORD }} | sudo -S docker compose -f Marisa_flight.yml build
            echo ${{ secrets.PASSWORD }} | sudo -S docker compose -f Marisa_flight.yml up -d
      - name: Telegram Notification
        uses: Dalenir/bumblebee@master
        with:
          bot_token: ${{ secrets.TEST_BOT_TOKEN }}
          chat_id: ${{ secrets.BOT_MASTER_ID }}
          message: '*Марисабот успешно размещен на сервере*'
          parse_mode: MarkdownV2